location="eastus"
rg-name="rg-rishabtf07-demo"
storage-account-name="rishabtf07demo"
index_document="index.html"
source_content="<h1>Hey Friends, this website was deployed with Terraform on Azure storage and is a bit advanced."